import gc
import json
import os
import shutil
import calendar

import numpy as np
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

# ============================================================
# Input paths
# ============================================================
code_num_path = PROJECT_ROOT / "Code_num.txt"
factor_dir = PROJECT_ROOT / "featureengineering/data/factors"
manifest_dir = PROJECT_ROOT / "featureengineering/data/manifests"
label_ret_1d_path = PROJECT_ROOT / "featureengineering/data/targets/label_ret_1d.fea"
label_ret_3d_path = PROJECT_ROOT / "featureengineering/data/targets/label_ret_3d.fea"
label_ret_5d_path = PROJECT_ROOT / "featureengineering/data/targets/label_ret_5d.fea"
label_ret_10d_path = PROJECT_ROOT / "featureengineering/data/targets/label_ret_10d.fea"
daily_adj_path = PROJECT_ROOT / "data/daily_adj.parquet"

# ============================================================
# Output paths (V7 data)
# ============================================================
out_dir = PROJECT_ROOT / "trainingdata"
fac_path = out_dir / "fac_all.fea"
trade_path = out_dir / "trade_amt.fea"

# Label outputs: one per target horizon
LABEL_TARGETS = {
    "label_ret_1d":  label_ret_1d_path,
    "label_ret_3d":  label_ret_3d_path,
    "label_ret_5d":  label_ret_5d_path,
    "label_ret_10d": label_ret_10d_path,
}

# ============================================================
# Config
# ============================================================
N_WORKERS = 48
BATCH_SIZE = 320
TMP_DIR = out_dir / "tmp_batches"

# --- Config for fac_sample generation ---
SAMPLE_N_FACTORS = 50          # Number of random factors for fac_sample.fea
SAMPLE_SEED = 42               # Random seed for reproducibility

# --- Config for factor selection strategies ---
# Default strategy used for fac_select.fea:
#   "minimal_filter" - remove only truly broken factors (zero-var, all-NaN, extreme NaN)
#   "ic_topk"        - top K factors by |mean(Spearman IC)| from quality results
#   "ic_positive"    - keep only factors with positive mean IC (directional filter)
#   "diverse"        - greedy diversified selection: balance IC + decorrelation
#   "model_importance" - top K by V7.X model-learned importance (factors_order.txt)
FAC_SELECT_STRATEGY = "hybrid"

# Strategy A: Minimal Filter (remove only truly broken factors)
MINIMAL_NAN_THRESHOLD = 0.5       # Extreme NaN ratio: remove if > this AND no valid IC
MINIMAL_VAR_THRESHOLD = 1e-12     # Zero-variance threshold

# Strategy B: IC Top-K (using quality_results.parquet rank_ic_mean)
IC_TOPK_K = 1100                  # Number of factors to keep

# Strategy C: IC Positive (keep only positive mean IC factors)
IC_POSITIVE_MIN_ICIR = 0.005      # Min |ICIR| to avoid pure-noise factors with IC~0

# Strategy D: Diverse Greedy (IC x decorrelation)
DIVERSE_K = 800                   # Target number of factors
DIVERSE_N_SAMPLE_DATES = 30       # Sampling dates for pairwise correlation
DIVERSE_N_SAMPLE_STOCKS = 300     # Sampling stocks for pairwise correlation

# --- Config for factor selection strategy E: Model Importance ---
# Uses factors_order.txt (generated from V7.X first-layer weight L1 norms)
# to select top-K factors by learned importance across all trained models.
MODEL_IMPORTANCE_TOP_K = 600        # Number of factors to keep
MODEL_IMPORTANCE_ORDER_PATH = PROJECT_ROOT / "Model/factors_order.txt"

# --- Input for factor quality metrics (generated by factor_quality.py) ---
QUALITY_RESULTS_PATH = PROJECT_ROOT / "featureengineering/quality/factor_quality_results.parquet"

# --- Output paths for factor subsets ---
fac_sample_path = out_dir / "fac_sample.fea"
fac_select_path = out_dir / "fac_select.fea"          # Default strategy output
fac_ic_topk_path = out_dir / "fac_IC_topK.fea"
fac_ic_positive_path = out_dir / "fac_IC_positive.fea"
fac_diverse_path = out_dir / "fac_diverse.fea"
fac_model_importance_path = out_dir / "fac_model_importance.fea"
fac_hybrid_path = out_dir / "fac_hybrid.fea"
fac_continuous_path = out_dir / "fac_continuous.fea"

# ============================================================
# Helper: load factor file, filter by cutoff date
# ============================================================
def _load_factor_stacked(path, cutoff=None):
    """Read a factor .fea file, optionally filter to dates > cutoff, stack to Series.
    Returns None if no data remains after filtering."""
    df = pd.read_feather(path)
    if cutoff is not None:
        df = df[df.index.astype(str) > str(cutoff)]
        if df.empty:
            return None
    return df.stack()


def _generate_fac_sample(fac_df, n_factors=SAMPLE_N_FACTORS, seed=SAMPLE_SEED):
    """
    Randomly sample n_factors from fac_df columns.

    Returns (fac_sample_df, list_of_sampled_factor_names).
    """
    all_factors = sorted(c for c in fac_df.columns if c not in ("date", "Code"))
    n_available = len(all_factors)
    if n_available == 0:
        raise RuntimeError("No factor columns found in data!")
    actual_n = min(n_factors, n_available)
    rng = np.random.default_rng(seed)
    sampled = sorted(rng.choice(all_factors, size=actual_n, replace=False).tolist())
    return fac_df[["date", "Code"] + sampled].copy(), sampled


# ============================================================
# Helper: identify continuous daily-frequency factors from upstream manifests
# ============================================================

# -- Classification of upstream data sources by frequency --
_DAILY_SOURCES = {
    "daily_adj.parquet", "daily.parquet", "finance.parquet",
    "cyq_perf.parquet", "main_fund_flow.parquet", "margin_detail.parquet",
    "limit_up.parquet", "dragon_tiger.parquet", "top_list.parquet",
    "limit_list.parquet", "ths_daily.parquet", "ths_sector_categories.parquet",
    "ths_constituent_stocks.parquet", "pledge_stat.parquet",
    "history_1min", "cyq_chips",       # raw upstream names (no .parquet suffix)
}

_NON_DAILY_SOURCES = {
    "financial_indicator.parquet", "balancesheet.parquet",
    "income.parquet", "cashflow.parquet",
    "holder_number.parquet", "index_weight.parquet",
    "stock_list.parquet",
}

_META_SOURCES = {"calendar.parquet"}
_FACTOR_MARKER = "__factors__"


def _identify_continuous_daily_factors(manifest_dir):
    """Identify factors whose upstream data sources are all daily-frequency.

    Reads every factor's manifest JSON and classifies it as daily or non-daily
    based on its dependency chain.  A factor is **daily** when all of its
    upstream data sources deliver new information every trading day (market
    data, intraday, fund flows, margin, etc.).  Factors that depend on
    quarterly/annual financial statements, shareholder registers, or index
    rebalance tables are **non-daily** even if their values are forward-filled
    to a daily grid.

    Coupling / enhanced factors (those whose manifest lists other factor names
    as dependencies) are resolved recursively: if every referenced factor is
    daily, the derived factor is also daily.

    Parameters
    ----------
    manifest_dir : Path
        Directory containing ``<factor_name>.json`` manifest files.

    Returns
    -------
    set of str
        Factor names classified as continuous daily-frequency.
    """
    if not manifest_dir.exists():
        print(f"  [ContinuousDaily] Manifest dir not found: {manifest_dir}")
        return set()

    # ---- load all manifests ----
    factors = {}       # name -> {category, factor_refs, data_refs}
    for fname in os.listdir(str(manifest_dir)):
        if not fname.endswith(".json"):
            continue
        with open(os.path.join(str(manifest_dir), fname)) as fh:
            data = json.load(fh)
        name = data["name"]
        deps = data.get("dependencies", [])

        factor_refs = []
        data_refs = []
        for d in deps:
            if d == _FACTOR_MARKER:
                continue
            if (d in _DAILY_SOURCES or d in _NON_DAILY_SOURCES
                    or d in _META_SOURCES or d.endswith(".parquet")):
                data_refs.append(d)
            else:
                factor_refs.append(d)          # reference to another factor

        factors[name] = {
            "category": data.get("category", "unknown"),
            "factor_refs": factor_refs,
            "data_refs": data_refs,
        }

    if not factors:
        print("  [ContinuousDaily] No manifests found.")
        return set()

    # ---- iterative resolution ----
    daily = set()
    non_daily = set()

    # First pass: classify by direct data sources
    for name, info in factors.items():
        real_sources = set(info["data_refs"]) - _META_SOURCES
        if real_sources & _NON_DAILY_SOURCES:
            non_daily.add(name)
        elif real_sources & _DAILY_SOURCES:
            daily.add(name)

    # Iteratively resolve factor references
    changed = True
    while changed:
        changed = False
        for name, info in factors.items():
            if name in daily or name in non_daily:
                continue
            # Re-check data refs (some may have been added after first pass)
            real_sources = set(info["data_refs"]) - _META_SOURCES
            if real_sources & _NON_DAILY_SOURCES:
                non_daily.add(name)
                changed = True
                continue
            elif real_sources & _DAILY_SOURCES:
                daily.add(name)
                changed = True
                continue
            # Resolve through factor references
            if info["factor_refs"]:
                if all(r in daily for r in info["factor_refs"]):
                    daily.add(name)
                    changed = True
                elif any(r in non_daily for r in info["factor_refs"]):
                    non_daily.add(name)
                    changed = True

    unresolved = set(factors) - daily - non_daily
    if unresolved:
        print(f"  [ContinuousDaily] WARNING: {len(unresolved)} factors could not be classified:")
        for n in sorted(unresolved)[:10]:
            print(f"    {n}: refs={factors[n]['factor_refs']}, data={factors[n]['data_refs']}")

    return daily




# ============================================================
# Helper: factor selection strategies (used in Sections 7-13)
# ============================================================

def _strategy_minimal_filter(fac_df, quality_df):
    """Strategy A: Remove only truly broken factors.

    Removes:
      - Zero-variance (xs_std_mean < threshold)
      - 100% NaN (nan_ratio > 0.999)
      - Extreme NaN (> threshold AND IC is NaN or zero-only)

    Keeps everything else - low IC, redundant, moderate NaN are all kept.
    The neural network handles weak/noisy signals.
    """
    all_cols = sorted(c for c in fac_df.columns if c not in ("date", "Code"))
    n_all = len(all_cols)

    q = quality_df.set_index("factor")

    remove = set()

    # Zero variance
    mask_zero = q["xs_std_mean"] < MINIMAL_VAR_THRESHOLD
    zero_var_factors = set(q.index[mask_zero])
    remove |= zero_var_factors
    print(f"  [MinimalFilter] Zero-variance: {len(zero_var_factors)} factors")

    # All NaN
    mask_allnan = q["nan_ratio"] > 0.999
    allnan_factors = set(q.index[mask_allnan])
    remove |= allnan_factors
    print(f"  [MinimalFilter] All-NaN: {len(allnan_factors)} factors")

    # Extreme NaN + no valid IC (cannot even measure predictive power)
    mask_extreme = (
        (q["nan_ratio"] > MINIMAL_NAN_THRESHOLD)
        & (q["rank_ic_mean"].isna() | (q["rank_icir"].abs() < 1e-10))
    )
    extreme_nan_factors = set(q.index[mask_extreme])
    remove |= extreme_nan_factors
    print(f"  [MinimalFilter] Extreme NaN+no IC: {len(extreme_nan_factors)} factors")

    keep_factors = sorted(set(all_cols) - remove)
    print(f"  [MinimalFilter] Total: {n_all} -> removed {len(remove)} -> kept {len(keep_factors)}")

    return keep_factors


def _strategy_ic_topk(quality_df, k=IC_TOPK_K):
    """Strategy B: Top K factors by |mean(Spearman IC)|.

    Uses rank_ic_mean from quality_results.parquet.
    Falls back to keeping all valid if K > available.
    """
    q = quality_df.copy()

    # Exclude factors with NaN IC (cannot be ranked)
    q_valid = q[q["rank_ic_mean"].notna()].copy()
    n_valid = len(q_valid)
    n_total = len(q)

    if q_valid.empty:
        raise RuntimeError("No factors with valid IC found in quality results!")

    # Rank by |mean IC| descending
    q_valid["abs_ic"] = q_valid["rank_ic_mean"].abs()
    q_valid = q_valid.sort_values("abs_ic", ascending=False)

    actual_k = min(k, n_valid)
    top_factors = q_valid["factor"].head(actual_k).tolist()

    print(f"  [IC-TopK] K={k}, valid IC factors={n_valid}/{n_total}")
    print(f"  [IC-TopK] Selected {len(top_factors)} factors")
    print(f"  [IC-TopK] |mean(IC)| range: [{q_valid['abs_ic'].iloc[actual_k-1]:.6f}, "
          f"{q_valid['abs_ic'].iloc[0]:.6f}]")

    # Show top 10
    print(f"  [IC-TopK] Top 10:")
    for i, (_, row) in enumerate(q_valid.head(10).iterrows()):
        print(f"    {i+1:2d}. {row['factor']:<50s} |mean(IC)|={row['abs_ic']:.6f}")

    return sorted(top_factors)


def _strategy_ic_positive(quality_df, min_icir=IC_POSITIVE_MIN_ICIR):
    """Strategy C: Keep only factors with positive mean IC.

    This filters out factors that have consistently negative predictive direction.
    Negative IC means the factor consistently predicts the OPPOSITE direction -
    these can confuse the neural network.

    A very low |ICIR| floor excludes factors where IC~0 from rounding noise.
    """
    q = quality_df.copy()

    mask = (
        q["rank_ic_mean"].notna()
        & (q["rank_ic_mean"] > 0)
        & (q["rank_icir"].abs() > min_icir)
    )
    keep = q[mask]
    n_pos = len(keep)
    n_neg = (q["rank_ic_mean"] < 0).sum()
    n_nan = q["rank_ic_mean"].isna().sum()
    n_noise = (q["rank_ic_mean"].notna() & (q["rank_icir"].abs() <= min_icir)).sum()

    print(f"  [IC-Positive] Positive mean IC: {n_pos}")
    print(f"  [IC-Positive] Negative mean IC (removed): {n_neg}")
    print(f"  [IC-Positive] NaN IC (removed): {n_nan}")
    print(f"  [IC-Positive] |ICIR| <= {min_icir} noise (removed): {n_noise}")
    print(f"  [IC-Positive] Total kept: {n_pos} / {len(q)}")

    return sorted(keep["factor"].tolist())


def _strategy_diverse_greedy(
    fac_df, quality_df, k=DIVERSE_K,
    n_dates=DIVERSE_N_SAMPLE_DATES, n_stocks=DIVERSE_N_SAMPLE_STOCKS
):
    """Strategy D: Greedy diversified factor selection.

    Balances signal strength (|mean IC|) with diversity (1 - max correlation to
    already-selected set). This produces a compact, non-redundant subset.

    Algorithm:
      1. Start with the factor with highest |mean(IC)|
      2. Iteratively add the factor that maximizes:
           score = |mean(IC)| * (1 - max_corr_to_selected)
      3. Stop when K factors are selected

    Correlation is computed on sampled dates x stocks to keep it tractable.
    """
    import warnings

    all_cols = sorted(c for c in fac_df.columns if c not in ("date", "Code"))
    n_all = len(all_cols)

    # Build quality lookup
    q = quality_df.set_index("factor")
    # Only consider factors with valid IC
    valid_cols = [c for c in all_cols if c in q.index and pd.notna(q.loc[c, "rank_ic_mean"])]
    if not valid_cols:
        raise RuntimeError("No factors with valid IC for diverse selection!")

    print(f"  [Diverse] Candidates: {len(valid_cols)} factors with valid IC, target K={k}")

    # Sample dates and stocks for correlation
    dates = sorted(fac_df["date"].unique())
    codes = sorted(fac_df["Code"].unique())

    step_d = max(1, len(dates) // n_dates)
    step_s = max(1, len(codes) // n_stocks)
    sample_dates = dates[::step_d][:n_dates]
    sample_codes = codes[::step_s][:n_stocks]

    print(f"  [Diverse] Sampling {len(sample_dates)} dates x {len(sample_codes)} stocks for correlation")

    # Extract factor values on sampled grid
    # Build a consistent date x code pivot table for each factor
    # Pre-compute the grid shape from the first factor to ensure alignment
    first_col = valid_cols[0]
    fac_sub = fac_df[
        fac_df["date"].isin(sample_dates) & fac_df["Code"].isin(sample_codes)
    ].copy()

    # Build a template pivot to get consistent (n_dates, n_codes) shape
    template_pivot = fac_sub.pivot_table(
        index="date", columns="Code", values=first_col, aggfunc="first"
    )
    n_rows, n_cols = template_pivot.shape
    n_samples = n_rows * n_cols
    template_dates = list(template_pivot.index)
    template_codes = list(template_pivot.columns)

    print(f"  [Diverse] Grid: {n_rows} dates x {n_cols} codes = {n_samples} samples")

    # Stack into 2D array: (n_samples, n_factors)
    mat = np.zeros((n_samples, len(valid_cols)), dtype=np.float64)
    for j, col in enumerate(valid_cols):
        # Pivot and reindex to match the template grid
        pivot = fac_sub.pivot_table(
            index="date", columns="Code", values=col, aggfunc="first"
        )
        pivot = pivot.reindex(index=template_dates, columns=template_codes)
        mat[:, j] = np.nan_to_num(pivot.values, nan=0.0).ravel()

    # Remove columns that are all-zero or constant (would produce NaN corr)
    col_std = mat.std(axis=0)
    good_mask = col_std > 1e-15
    good_indices = np.where(good_mask)[0]
    good_cols = [valid_cols[i] for i in good_indices]
    mat_good = mat[:, good_mask]

    print(f"  [Diverse] {len(good_cols)} factors with non-zero variance on sampled grid")

    if k >= len(good_cols):
        print(f"  [Diverse] K={k} >= available={len(good_cols)}, keeping all valid")
        return sorted(good_cols)

    # Compute correlation matrix (only once, on the good subset)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        corr = np.corrcoef(mat_good.T)
        corr = np.nan_to_num(corr, nan=0.0)

    n_good = len(good_cols)
    # Map good index -> IC lookup
    ic_abs = np.array([abs(q.loc[c, "rank_ic_mean"]) for c in good_cols])

    # Greedy selection
    selected_indices = []
    remaining = set(range(n_good))

    # Start with highest |IC|
    first = int(np.argmax(ic_abs))
    selected_indices.append(first)
    remaining.remove(first)

    for iteration in range(1, k):
        best_idx = -1
        best_score = -1.0

        for cand in remaining:
            # Max absolute correlation to any selected factor
            max_corr = max(abs(corr[cand, s]) for s in selected_indices)
            # Score: IC * (1 - max_corr)
            score = ic_abs[cand] * (1.0 - max_corr)
            if score > best_score:
                best_score = score
                best_idx = cand

        if best_idx < 0:
            break

        selected_indices.append(best_idx)
        remaining.remove(best_idx)

        if (iteration + 1) % 200 == 0:
            print(f"  [Diverse] Selected {iteration + 1}/{k} factors...")

    selected_factors = [good_cols[i] for i in selected_indices]

    # Show stats
    selected_ic = [ic_abs[i] for i in selected_indices]
    print(f"  [Diverse] Selected {len(selected_factors)} factors")
    print(f"  [Diverse] |mean(IC)| range: [{min(selected_ic):.6f}, {max(selected_ic):.6f}]")

    # Average pairwise correlation among selected
    sel_corr = corr[np.ix_(selected_indices, selected_indices)]
    n_sel = len(selected_indices)
    if n_sel > 1:
        triu_idx = np.triu_indices(n_sel, k=1)
        avg_corr = sel_corr[triu_idx].mean()
        max_corr = sel_corr[triu_idx].max()
        print(f"  [Diverse] Selected avg corr: {avg_corr:.4f}, max corr: {max_corr:.4f}")
    else:
        print(f"  [Diverse] Only 1 factor selected, no pairwise corr to report")

    del mat, mat_good, corr, fac_sub
    gc.collect()

    return sorted(selected_factors)


def _strategy_model_importance(factor_names, order_path=MODEL_IMPORTANCE_ORDER_PATH, k=MODEL_IMPORTANCE_TOP_K):
    """Strategy E: Top K factors by model-learned importance.

    Reads factors_order.txt (generated from V7.X first-layer weight L1 norms),
    selects top-K factors by combined importance score across 5 trained models.

    This reflects what the models actually learned to use, not just statistical IC.
    """
    importance = {}
    with open(order_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) >= 3:
                name = parts[1].strip()
                try:
                    score = float(parts[2].strip())
                    importance[name] = score
                except ValueError:
                    continue

    # Only keep factors that exist in both the ranking and the data
    available = sorted(set(factor_names) & set(importance.keys()))
    if not available:
        raise RuntimeError(
            f"No factors from factors_order.txt found in data! "
            f"Check: {order_path}"
        )

    # Sort by importance score descending
    available_sorted = sorted(available, key=lambda x: importance.get(x, 0), reverse=True)
    actual_k = min(k, len(available_sorted))

    selected = available_sorted[:actual_k]

    print(f"  [ModelImportance] Ranked factors available: {len(available)}/{len(factor_names)}")
    print(f"  [ModelImportance] K={k}, selected {len(selected)} factors")
    print(f"  [ModelImportance] Score range: [{importance.get(selected[-1], 0):.6f}, "
          f"{importance.get(selected[0], 0):.6f}]")
    print(f"  [ModelImportance] Top 10:")
    for i, name in enumerate(selected[:10]):
        print(f"    {i+1:2d}. {name:<50s} score={importance[name]:.6f}")

    return selected



# --- Config for Strategy F: Hybrid (IC + Model Importance + Diverse) ---
HYBRID_IC_TOPK = 200               # Top K by |IC| for standalone signal
HYBRID_MODEL_TOPK = 400            # Top K by model importance for interactions
HYBRID_DIVERSE_K = 200             # Additional factors from Diverse Greedy
HYBRID_TOTAL_K = 800               # Target total (IC_TopK + Model_TopK + Diverse_K)
HYBRID_ORDER_PATH = PROJECT_ROOT / "Model/factors_order.txt"


def _strategy_hybrid(fac_df, quality_df, order_path=HYBRID_ORDER_PATH):
    """Strategy F: Hybrid selection balancing IC signal + model interactions + diversity.

    Problem: Only 9 factors overlap between Top-100 by |IC| and Top-100 by model
    importance.  The model ignores the strongest standalone signals (volatility,
    microstructure) while heavily using low-IC fundamental factors for interactions.

    Solution:
      1. Pick top IC_TOPK by |IC| - guarantees strongest standalone signals
      2. Pick top MODEL_TOPK by model-learned importance - guarantees interaction coverage
      3. De-duplicate the union of (1) and (2)
      4. Fill remaining slots via Diverse Greedy from the unused pool

    Total target: HYBRID_TOTAL_K factors.
    """
    all_cols = sorted(c for c in fac_df.columns if c not in ("date", "Code"))
    n_all = len(all_cols)
    q = quality_df.set_index("factor")

    # Step 1: Top K by |IC|
    valid_ic = [c for c in all_cols
                if c in q.index and pd.notna(q.loc[c, "rank_ic_mean"])]
    ic_abs = {c: abs(q.loc[c, "rank_ic_mean"]) for c in valid_ic}
    ic_sorted = sorted(ic_abs, key=ic_abs.get, reverse=True)
    ic_pick = set(ic_sorted[:min(HYBRID_IC_TOPK, len(ic_sorted))])

    print(f"  [Hybrid] Step 1: IC Top-{HYBRID_IC_TOPK} -> {len(ic_pick)} factors")
    if ic_pick:
        print(f"  [Hybrid]   |IC| range: [{min(ic_abs[c] for c in ic_pick):.6f}, "
              f"{max(ic_abs[c] for c in ic_pick):.6f}]")

    # Step 2: Top K by model importance
    importance = {}
    if order_path.exists():
        with open(order_path) as f:
            for line in f:
                parts = line.strip().split(chr(9))  # tab
                if len(parts) >= 3:
                    try:
                        importance[parts[1].strip()] = float(parts[2].strip())
                    except ValueError:
                        continue

    available_imp = sorted(
        set(all_cols) & set(importance.keys()),
        key=lambda x: importance.get(x, 0), reverse=True
    )
    imp_pick = set(available_imp[:min(HYBRID_MODEL_TOPK, len(available_imp))])

    print(f"  [Hybrid] Step 2: Model Top-{HYBRID_MODEL_TOPK} -> {len(imp_pick)} factors")
    if imp_pick:
        print(f"  [Hybrid]   Score range: [{min(importance.get(c, 0) for c in imp_pick):.2f}, "
              f"{max(importance.get(c, 0) for c in imp_pick):.2f}]")

    # Step 3: Union
    union = ic_pick | imp_pick
    print(f"  [Hybrid] Step 3: Union = {len(union)} factors "
          f"(overlap={len(ic_pick & imp_pick)})")

    # Step 4: Fill remaining with Diverse Greedy
    remaining_k = max(0, HYBRID_TOTAL_K - len(union))

    if remaining_k > 0 and quality_df is not None:
        candidates = sorted(set(valid_ic) - union)
        if len(candidates) > remaining_k:
            print(f"  [Hybrid] Step 4: Diverse Greedy on {len(candidates)} "
                  f"candidates for {remaining_k} slots...")
            diverse_pick = _strategy_diverse_greedy_on_subset(
                fac_df, quality_df, candidates, k=remaining_k
            )
            union |= set(diverse_pick)
        else:
            union |= set(candidates)
            print(f"  [Hybrid] Step 4: Only {len(candidates)} candidates, adding all")

    final = sorted(union)
    print(f"  [Hybrid] Final: {len(final)} factors selected")
    print(f"  [Hybrid]   IC-sourced: {len(ic_pick & set(final))}")
    print(f"  [Hybrid]   Model-sourced: {len(imp_pick & set(final))}")
    print(f"  [Hybrid]   Overlap (in both): {len(ic_pick & imp_pick)}")

    return final


def _strategy_diverse_greedy_on_subset(fac_df, quality_df, candidate_cols, k=200):
    """Run Diverse Greedy on a pre-filtered subset of factor columns."""
    import warnings

    q = quality_df.set_index("factor")

    dates = sorted(fac_df["date"].unique())
    codes = sorted(fac_df["Code"].unique())
    n_dates, n_stocks = DIVERSE_N_SAMPLE_DATES, DIVERSE_N_SAMPLE_STOCKS
    step_d = max(1, len(dates) // n_dates)
    step_s = max(1, len(codes) // n_stocks)
    sample_dates = dates[::step_d][:n_dates]
    sample_codes = codes[::step_s][:n_stocks]

    fac_sub = fac_df[
        fac_df["date"].isin(sample_dates) & fac_df["Code"].isin(sample_codes)
    ].copy()

    first_col = candidate_cols[0]
    template_pivot = fac_sub.pivot_table(
        index="date", columns="Code", values=first_col, aggfunc="first"
    )
    n_rows, n_cols = template_pivot.shape
    n_samples = n_rows * n_cols

    mat = np.zeros((n_samples, len(candidate_cols)), dtype=np.float64)
    for j, col in enumerate(candidate_cols):
        pivot = fac_sub.pivot_table(
            index="date", columns="Code", values=col, aggfunc="first"
        )
        pivot = pivot.reindex(index=template_pivot.index, columns=template_pivot.columns)
        mat[:, j] = np.nan_to_num(pivot.values, nan=0.0).ravel()

    col_std = mat.std(axis=0)
    good_mask = col_std > 1e-15
    good_indices = np.where(good_mask)[0]
    good_cols = [candidate_cols[i] for i in good_indices]
    mat_good = mat[:, good_mask]

    if k >= len(good_cols):
        return sorted(good_cols)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        corr = np.corrcoef(mat_good.T)
        corr = np.nan_to_num(corr, nan=0.0)

    ic_abs = np.array([abs(q.loc[c, "rank_ic_mean"]) for c in good_cols])
    selected_indices = [int(np.argmax(ic_abs))]
    remaining = set(range(len(good_cols))) - {selected_indices[0]}

    for _ in range(1, k):
        best_idx, best_score = -1, -1.0
        for cand in remaining:
            max_corr = max(abs(corr[cand, s]) for s in selected_indices)
            score = ic_abs[cand] * (1.0 - max_corr)
            if score > best_score:
                best_score, best_idx = score, cand
        if best_idx < 0:
            break
        selected_indices.append(best_idx)
        remaining.remove(best_idx)

    selected = [good_cols[i] for i in selected_indices]
    del mat, mat_good, corr, fac_sub
    gc.collect()
    return sorted(selected)




def _save_factor_subset(fac_df, keep_factors, output_path, label=""):
    """Save a factor subset as .fea file. Returns the saved DataFrame."""
    keep_cols = ["date", "Code"] + keep_factors
    keep_cols = [c for c in keep_cols if c in fac_df.columns]
    result = fac_df[keep_cols].copy()
    result.to_feather(output_path)
    print(f"  [{label}] Saved: {output_path}")
    print(f"  [{label}] Shape: {result.shape}  (date + Code + {len(keep_factors)} factors)")
    return result


# ============================================================
# Setup
# ============================================================
out_dir.mkdir(parents=True, exist_ok=True)

with open(code_num_path) as f:
    allowed_codes = [line.strip() for line in f if line.strip()]
allowed_codes_set = set(allowed_codes)
print(f"Loaded {len(allowed_codes)} codes from {code_num_path}")

# ============================================================
# 1. Merge factors (batch-processed to avoid OOM)
# ============================================================
files = sorted(factor_dir.glob("*.fea"))
if not files:
    raise FileNotFoundError(f"No .fea files found in {factor_dir}")

# --- Incremental detection ---
incremental_fac = fac_path.exists()
cutoff_date = None

if incremental_fac:
    print(f"Found existing factors, incremental mode...")
    _tmp = pd.read_feather(fac_path, columns=["date"])
    cutoff_date = _tmp["date"].max()
    del _tmp; gc.collect()
    print(f"  Max date in existing: {cutoff_date}, will only process newer dates")
else:
    print(f"No existing factor file, full generation...")

print(f"Found {len(files)} factor files, loading with {N_WORKERS} workers...")

# Clean up leftover temp files from previous failed runs
if TMP_DIR.exists():
    shutil.rmtree(TMP_DIR)
TMP_DIR.mkdir(parents=True, exist_ok=True)

batches = [files[i:i + BATCH_SIZE] for i in range(0, len(files), BATCH_SIZE)]
batch_paths = []
all_factor_cols = set()

for batch_idx, batch_files in enumerate(batches):
    series_list = []
    with ThreadPoolExecutor(max_workers=N_WORKERS) as pool:
        futures = {pool.submit(_load_factor_stacked, f, cutoff_date): f.stem
                   for f in batch_files}
        for fut in tqdm(as_completed(futures), total=len(batch_files),
                        desc=f"Batch {batch_idx+1}/{len(batches)}"):
            s = fut.result()
            if s is None:
                continue
            s.name = futures[fut]
            s = s.astype(np.float32)
            series_list.append(s)

    if not series_list:
        del series_list
        gc.collect()
        continue

    batch_df = pd.concat(series_list, axis=1).copy()
    del series_list
    gc.collect()

    batch_df.reset_index(inplace=True)
    batch_df.rename(columns={"Date": "date"}, inplace=True)
    batch_df["Code"] = batch_df["Code"].astype(str).str.replace(".BJ", "", regex=False)
    batch_df["date"] = batch_df["date"].astype(str)
    batch_df = batch_df[batch_df["Code"].isin(allowed_codes_set)]

    if batch_df.empty:
        del batch_df
        gc.collect()
        continue

    all_factor_cols.update(c for c in batch_df.columns if c not in ("date", "Code"))

    batch_path = TMP_DIR / f"batch_{batch_idx:03d}.fea"
    batch_df.to_feather(batch_path)
    batch_paths.append(batch_path)
    del batch_df
    gc.collect()

# --- Merge ---
if not batch_paths:
    print("No new factor data to merge. Keeping existing file.")
    if incremental_fac:
        merged = pd.read_feather(fac_path)
        factor_cols = sorted(c for c in merged.columns if c not in ("date", "Code"))
    else:
        raise RuntimeError("No factor data processed and no existing file!")
else:
    print(f"\nMerging {len(batch_paths)} batches (indexed concat)...")
    dfs = []
    for bp in tqdm(batch_paths, desc="Reading & indexing"):
        dfs.append(pd.read_feather(bp).set_index(["date", "Code"]))

    new_merged = pd.concat(dfs, axis=1)
    del dfs
    gc.collect()

    if incremental_fac:
        existing = pd.read_feather(fac_path).set_index(["date", "Code"])
        combined = pd.concat([existing, new_merged])
        combined = combined[~combined.index.duplicated(keep="last")]
        del existing, new_merged
        gc.collect()
    else:
        combined = new_merged

    combined.reset_index(inplace=True)
    factor_cols = sorted(c for c in combined.columns if c not in ("date", "Code"))
    combined = combined[["date", "Code"] + factor_cols]
    combined.sort_values(["date", "Code"], inplace=True)
    combined.reset_index(drop=True, inplace=True)

    print(f"Merged shape: {combined.shape}")
    print(f"Factor columns: {len(factor_cols)}")

    combined.to_feather(fac_path)
    print(f"Saved factors to {fac_path}")
    del combined
    gc.collect()

# Clean up temp files
if TMP_DIR.exists():
    shutil.rmtree(TMP_DIR)
print("Cleaned up temp batch files")

# ============================================================
# 2. Generate labels (1d, 3d, 5d, 10d)
# ============================================================
for label_name, label_src_path in LABEL_TARGETS.items():
    label_out_path = out_dir / f"{label_name}.fea"
    incremental_label = label_out_path.exists()

    if incremental_label:
        print(f"\n[{label_name}] Found existing label, incremental mode...")
        _tmp = pd.read_feather(label_out_path, columns=["index"])
        max_label_date = _tmp["index"].max()
        del _tmp; gc.collect()
        print(f"  Max date in existing: {max_label_date}")

        print(f"  Loading {label_name}.fea source...")
        label_source = pd.read_feather(label_src_path)
        new_rows_mask = label_source.index.astype(str) > str(max_label_date)
        label_new = label_source[new_rows_mask]

        if label_new.empty:
            print(f"  No new label data, skipping.")
        else:
            print(f"  {len(label_new)} new dates found, processing...")
            existing_label = pd.read_feather(label_out_path)

            label_new = label_new.reset_index().rename(columns={"Date": "index"})
            label_new["index"] = label_new["index"].astype(str)
            label_new_cols = ["index"] + [c for c in label_new.columns
                                           if c != "index" and c in allowed_codes_set]
            label_new = label_new[label_new_cols]

            combined = pd.concat([existing_label, label_new], ignore_index=True)
            combined.drop_duplicates(subset=["index"], keep="last", inplace=True)
            combined.sort_values("index", inplace=True)
            combined.reset_index(drop=True, inplace=True)

            print(f"  [{label_name}] shape: {combined.shape}")
            combined.to_feather(label_out_path)
            print(f"  Saved to {label_out_path}")
            del existing_label, label_new, combined
            gc.collect()
        del label_source
        gc.collect()
    else:
        print(f"\n[{label_name}] No existing label, full generation...")
        print(f"  Loading {label_name}.fea source...")
        label_df = pd.read_feather(label_src_path)

        print("  Processing label...")
        label = label_df.reset_index()
        label = label.rename(columns={"Date": "index"})
        label["index"] = label["index"].astype(str)

        label_cols = ["index"] + [c for c in label.columns if c != "index" and c in allowed_codes_set]
        label = label[label_cols]

        print(f"  [{label_name}] shape: {label.shape}")
        label.to_feather(label_out_path)
        print(f"  Saved to {label_out_path}")
        del label, label_df
        gc.collect()

# ============================================================
# 3. Generate trade_amt
# ============================================================
incremental_trade = trade_path.exists()

if incremental_trade:
    print(f"\nFound existing trade_amt, incremental mode...")
    _tmp = pd.read_feather(trade_path, columns=["index"])
    max_trade_date = _tmp["index"].max()
    del _tmp; gc.collect()
    print(f"  Max date in existing: {max_trade_date}")

    print("Loading daily_adj.parquet...")
    trade_df = pd.read_parquet(daily_adj_path,
                               columns=["stock_code", "trade_date", "amount"])

    trade_df["date_str"] = trade_df["trade_date"].str.replace("-", "", regex=False)
    trade_df = trade_df[trade_df["date_str"] > str(max_trade_date)]

    if trade_df.empty:
        print("No new trade data, skipping.")
    else:
        print(f"  {len(trade_df)} new rows, processing...")
        existing_trade = pd.read_feather(trade_path)

        trade_df["Code"] = trade_df["stock_code"].str.replace(r"\.(SZ|SH|BJ)$", "", regex=True)
        trade_df = trade_df[trade_df["Code"].isin(allowed_codes_set)]
        print(f"  Filtered to {len(trade_df)} rows, pivoting...")

        trade_new = trade_df.pivot_table(index="date_str", columns="Code",
                                         values="amount", aggfunc="first")
        trade_new.reset_index(inplace=True)
        trade_new.rename(columns={"date_str": "index"}, inplace=True)

        combined = pd.concat([existing_trade, trade_new], ignore_index=True)
        combined.drop_duplicates(subset=["index"], keep="last", inplace=True)
        combined.sort_values("index", inplace=True)
        combined.reset_index(drop=True, inplace=True)

        print(f"trade_amt shape: {combined.shape}")
        combined.to_feather(trade_path)
        print(f"Saved trade_amt to {trade_path}")
        del existing_trade, trade_new, combined
        gc.collect()
    del trade_df
    gc.collect()
else:
    print("\nNo existing trade_amt, full generation...")
    print("Loading daily_adj.parquet...")
    trade_df = pd.read_parquet(daily_adj_path,
                               columns=["stock_code", "trade_date", "amount"])

    trade_df["Code"] = trade_df["stock_code"].str.replace(r"\.(SZ|SH|BJ)$", "", regex=True)
    trade_df["date"] = pd.to_datetime(trade_df["trade_date"]).dt.strftime("%Y%m%d")

    trade_df = trade_df[trade_df["Code"].isin(allowed_codes_set)]
    print(f"Filtered to {len(trade_df)} rows, pivoting...")
    trade_amt = trade_df.pivot_table(index="date", columns="Code",
                                     values="amount", aggfunc="first")

    trade_amt.reset_index(inplace=True)
    trade_amt.rename(columns={"date": "index"}, inplace=True)

    print(f"trade_amt shape: {trade_amt.shape}")
    trade_amt.to_feather(trade_path)
    print(f"Saved trade_amt to {trade_path}")
    del trade_amt, trade_df
    gc.collect()

# ============================================================
# 4. Generate fac_sample.fea (random 50-factor subset for quick testing)
# ============================================================
print(f"\n{'='*60}")
print(f"[4] Generating fac_sample.fea ({SAMPLE_N_FACTORS} random factors, seed={SAMPLE_SEED})...")

fac_all = pd.read_feather(fac_path)
print(f"  Loaded fac_all: {fac_all.shape}")

fac_sample_df, sampled_factors = _generate_fac_sample(
    fac_all, n_factors=SAMPLE_N_FACTORS, seed=SAMPLE_SEED
)
fac_sample_df.to_feather(fac_sample_path)
print(f"  Saved: {fac_sample_path}")
print(f"  Shape: {fac_sample_df.shape}")
print(f"  Sampled factors ({len(sampled_factors)}):")
for i, fn in enumerate(sampled_factors):
    print(f"    {i+1:2d}. {fn}")
del fac_sample_df
gc.collect()

# ============================================================
# 5. Generate fac_continuous.fea (continuous daily-frequency factors only)
# ============================================================
print(f"\n{'='*60}")
print(f"[5] Generating fac_continuous.fea (continuous daily-frequency factors)...")

fac_all = pd.read_feather(fac_path)
print(f"  Loaded fac_all: {fac_all.shape}")

# Identify which columns in fac_all are continuous daily-frequency factors
daily_factor_names = _identify_continuous_daily_factors(manifest_dir)
print(f"  Identified {len(daily_factor_names)} continuous daily-frequency factors from manifests")

# Intersect with columns actually present in fac_all
fac_all_cols = set(c for c in fac_all.columns if c not in ("date", "Code"))
continuous_factors = sorted(daily_factor_names & fac_all_cols)

n_total = len(fac_all_cols)
n_continuous = len(continuous_factors)
n_missing = len(daily_factor_names - fac_all_cols)

print(f"  Total factor columns in fac_all: {n_total}")
print(f"  Continuous daily factors matched: {n_continuous}")
if n_missing > 0:
    print(f"  Factors in manifests but not in fac_all: {n_missing}")

# Show category breakdown
daily_cats = {}
for name in continuous_factors:
    # Read manifest for category (we already loaded it but let's use a lightweight check)
    manifest_path = manifest_dir / f"{name}.json"
    try:
        with open(manifest_path) as fh:
            manifest_data = json.load(fh)
        cat = manifest_data.get("category", "unknown")
    except Exception:
        cat = "unknown"
    daily_cats[cat] = daily_cats.get(cat, 0) + 1

print(f"  Category breakdown:")
for cat, cnt in sorted(daily_cats.items(), key=lambda x: -x[1]):
    print(f"    {cat}: {cnt}")

_save_factor_subset(fac_all, continuous_factors, fac_continuous_path, "ContinuousDaily")
del fac_all
gc.collect()

# ============================================================
# 6. Load quality metrics for factor selection strategies
# ============================================================
print(f"\n{'='*60}")
print(f"[5] Loading factor quality metrics...")

quality_df = None

if not QUALITY_RESULTS_PATH.exists():
    print(f"  [WARNING] Quality results not found: {QUALITY_RESULTS_PATH}")
    print(f"  Run featureengineering/quality/factor_quality.py first.")
    print(f"  Falling back: fac_select.fea = fac_all.fea (no filtering)")
else:
    quality_df = pd.read_parquet(QUALITY_RESULTS_PATH)
    n_q = len(quality_df)
    n_valid_ic = quality_df["rank_ic_mean"].notna().sum()
    print(f"  Loaded {n_q} factors from quality results")
    print(f"  Factors with valid IC: {n_valid_ic}")
    print(f"  |mean(IC)| stats: "
          f"median={quality_df['rank_ic_mean'].abs().median():.6f}, "
          f"P90={quality_df['rank_ic_mean'].abs().quantile(0.9):.6f}")
    print(f"  NaN ratio stats: "
          f"median={quality_df['nan_ratio'].median():.4f}, "
          f"P95={quality_df['nan_ratio'].quantile(0.95):.4f}")


# ============================================================
# 10. Strategy D: Diverse Greedy Selection
# ============================================================
if quality_df is not None:
    print(f"\n{'='*60}")
    print(f"[9] Strategy D: Diverse Greedy (K={DIVERSE_K})...")
    print(f"  Sampling: {DIVERSE_N_SAMPLE_DATES} dates x {DIVERSE_N_SAMPLE_STOCKS} stocks")

    fac_all = pd.read_feather(fac_path)
    try:
        keep_diverse = _strategy_diverse_greedy(
            fac_all, quality_df, k=DIVERSE_K,
            n_dates=DIVERSE_N_SAMPLE_DATES, n_stocks=DIVERSE_N_SAMPLE_STOCKS
        )
        _save_factor_subset(fac_all, keep_diverse, fac_diverse_path, "Diverse")
    except Exception as e:
        print(f"  [Diverse] ERROR: {e}")
        print(f"  [Diverse] Skipping - falling back to minimal filter for this strategy")
        import traceback
        traceback.print_exc()
        keep_diverse = _strategy_minimal_filter(fac_all, quality_df)
        _save_factor_subset(fac_all, keep_diverse, fac_diverse_path, "Diverse-Fallback")
    del fac_all
    gc.collect()


# ============================================================
# 13. Strategy F: Hybrid (IC + Model Importance + Diverse)
# ============================================================
if quality_df is not None:
    print(f"\n{'='*60}")
    print(f"[12] Strategy F: Hybrid (IC={HYBRID_IC_TOPK} + Model={HYBRID_MODEL_TOPK} + Diverse={HYBRID_DIVERSE_K})...")

    fac_all = pd.read_feather(fac_path)
    try:
        keep_hybrid = _strategy_hybrid(fac_all, quality_df, order_path=HYBRID_ORDER_PATH)
        _save_factor_subset(fac_all, keep_hybrid, fac_hybrid_path, "Hybrid")
    except Exception as e:
        print(f"  [Hybrid] ERROR: {e}")
        import traceback
        traceback.print_exc()
    del fac_all
    gc.collect()

# ============================================================
# Summary
# ============================================================
print(f"\n{'='*60}")
print(f"Factor Selection Summary")
print(f"{'='*60}")
print(f"  Default strategy: {FAC_SELECT_STRATEGY}")
print(f"  fac_all.fea:      {fac_path}")
print(f"  fac_select.fea:   {fac_select_path}")
print(f"  fac_continuous.fea: {fac_continuous_path}")
if quality_df is not None:
    print(f"  Also generated:")
    print(f"    fac_IC_topK.fea:              {fac_ic_topk_path}")
    print(f"    fac_IC_positive.fea:          {fac_ic_positive_path}")
    print(f"    fac_diverse.fea:              {fac_diverse_path}")
    print(f"    fac_model_importance.fea:     {fac_model_importance_path}")
print(f"\nAll done.")

