# 最佳四人组搜索报告（2026-06-28 更新）

> **搜索时间**: 2026-06-28 19:32–19:55 (~22 min)  
> **搜索范围**: 29 个存活模型（V0.3 ~ V5.8，包含所有 5 代仍保留 model_res 的模型）  
> **回测区间**: 2025-01-02 ~ 2026-06-08（344 个交易日，1,782 只股票）  
> **评价方式**: 流动性加权合成收益率（1.5e9 资金规模）+ Rank IC  
> **组合数**: C(29,4) = **23,751 个**  
> **并行**: 20 workers  
> **搜索耗时**: 1,354s (~22 min)

---

##   P0: 搜索结果使用前必读 — V5.0 复制事故

V5.0 的 `model_res` 与 V4.1 **MD5 完全一致**（`484392fc4d3a5c34bb5812bd31e58dcb`）——这是文件级复制而非独立训练。本报告中：
- **任何包含 V5.0 的组合 = V4.1 的等价组合**，不作为独立候选
- V0.3 = V1.0（V0.3 是 V1.0 的早期命名）
- 推荐组合中已将 V5.0 排除，如有 V5.0 出现会标注 `≈ V4.1`

---

##   关键发现：V5.1（Factor Attention）— 从灾难到 MVP

**V5.X 最惊人的发现**：V5.1（Factor Attention）在单人战中惨败（Top 1 年化 153.69%，-58.6% vs Baseline，**V5.X 全系列最差**），但在团队战中成为 **不可或缺的核心成员**：

| 维度 | V5.1 出现频率 | 排名 |
|------|:---:|:---:|
| Top 50 TR 组合 | 11/50 | 第 6 |
| Top 50 IC 组合 | 24/50 | **第 3** |
| Top 50 综合组合 | 26/50 | **第 2** |
| 三维度联合 Top 150 | **61/150** | **第 3** |

**V5.1 是经典的"多样化错误"收益者**：它的 4-head Self-Attention 学到了与所有其他 MLP 模型截然不同的因子交互模式——虽然这些模式在 Top 1 选股上无效（-58.6% TR），但它们提供了其他模型完全不具备的排序信号维度。在四人组中，V5.1 的作用是**降低相关性而非提升准确率**——这正是集成的核心价值。

---

##   冠军组合

### ★ Top_Return 最高组 — 绝对收益最优（推荐）

| 成员 | 代际 | 单人 Top_Return | 单人 IC |
|------|:----:|:------:|:------:|
| **V1.0** | V1 Baseline | 1.1365 | 0.0532 |
| **V2.1** | V2 Kendall | 0.9784 | 0.0519 |
| **V3.2** | V3 R-Drop on Clean | 1.1116 | 0.0524 |
| **V3.7** | V3 CD+FP65% | 1.0408 | 0.0423 |

| 指标 | 四人组值 | vs 单人最优(V4.1 TR=1.4745) | vs 旧冠军(V2.1+V3.2+V3.7+V1.2) |
|------|:------:|:------:|:------:|
| **top_return** | **1.2875** | -12.7% | **+3.0%** |
| **IC** | **0.05547** | +3.7% vs V4.1 IC | +0.1% |

> **这是当前所有 29 个模型中的最强四人组（TR 维度）。** 将旧冠军中的 V1.2 替换为 V1.0 后，TR 从 1.2505 提升至 1.2875（+3.0%）。V1.0 的"朴素性"（无 softmax 权重、无强正则化）提供了与 V1.2 不同的信号维度——在四人组中，一个"简单但不同"的模型比一个"优化过但类似"的模型更有价值。

**备选（等价）**: V0.3 + V2.1 + V3.2 + V3.7（V0.3 = V1.0，结果完全一致）

---

### ★ 综合得分最高组 — TR+IC 均衡最优

| 成员 | 代际 | 单人 Top_Return | 单人 IC |
|------|:----:|:------:|:------:|
| **V1.2** | V1 冠军 | 1.3533 | 0.0530 |
| **V3.7** | V3 CD+FP65% | 1.0408 | 0.0423 |
| **V4.1** | V4 冠军 | 1.4745 | 0.0535 |
| **V5.1** | V5 Factor Attention | 0.6099 | 0.0460 |

| 指标 | 四人组值 | vs 单人最优(V4.1) |
|------|:------:|:------:|
| **top_return** | **1.1606** | -21.3% |
| **IC** | **0.05668** | +5.9% vs V4.1 IC |
| **composite_z** | **3.99** | 23,751 组中最高 |

> **TR 与 IC 的最佳平衡。** V4.1（单人 TR 冠军）提供主攻火力，V3.7 提供防御多样性，V1.2 提供稳定排序，V5.1 提供正交信号。四人组的 IC=0.05668 超越 V4.0 Baseline（IC=0.0559），是兼顾收益与排序的最优解。

**注意**：旧综合冠军是 V2.1+V3.2+V3.7+V1.2_copy（TR=1.2505, IC=0.0554），新综合冠军牺牲了部分 TR（-7.2%）换取了更高的 IC（+2.3%）。V5.1 的加入提升了 IC 但拖累了 TR。

---

### ★ IC 最高组 — 排序精度最优

| 成员 | 代际 | 单人 IC | 单人 Top_Return |
|------|:----:|:------:|:------:|
| **V2.8** | V2 GC 冠军 | 0.0559 | 1.2100 |
| **V4.0** | V4 GC Baseline | 0.0559 | 1.1706 |
| **V5.1** | V5 Factor Attention | 0.0460 | 0.6099 |
| **V5.6** | V5 Reduced Mixup | 0.0525 | 1.2221 |

| 指标 | 四人组值 | vs 单人 IC 最优(V2.0 IC=0.0563) |
|------|:------:|:------:|
| **top_return** | **0.9310** | — |
| **IC** | **0.05772** | **+2.5%** |

> **IC=0.05772 创造了所有 29 个模型组合中的最高排序精度。** V2.8+V4.0 两个 GC 基线提供排序稳定性骨架，V5.1+V5.6 提供正交信号。适合需要高排序精度的大规模选股场景（Top 100–500）。

---

##   Top 15 排名

### 按 Top_Return 排名（去重 V5.0/V0.3 等价组合）

| # | 组合 | top_return | IC | 备注 |
|:---:|------|:------:|:------:|------|
| **1** | **V1.0 + V2.1 + V3.2 + V3.7** | **1.2875** | 0.05547 | **★ 新冠军！** V1.0 替代 V1.2 |
| 2 | V1.2 + V2.1 + V3.2 + V3.7 | 1.2505 | 0.05539 | 旧冠军（验证通过） |
| 3 | V1.2 + V3.7 + V4.1 + V5.1 | 1.1606 | 0.05668 | **★ 综合冠军** V5.1 首次上榜 |
| 4 | V1.2 + V2.1 + V3.7 + V4.1 | 1.1958 | 0.05594 | V4.1 替代 V3.2 |
| 5 | V1.2 + V2.1 + V3.3 + V3.7 | 1.1937 | 0.05408 | V3.3(Kendall) 替代 V3.2 |
| 6 | V1.2 + V2.3 + V3.2 + V3.7 | 1.1863 | 0.05360 | V2.3(CD) 替代 V2.1 |
| 7 | V1.2 + V1.8 + V4.4 + V5.1 | 1.1980 | 0.05518 | **新组合** V5.1+剪枝系列 |
| 8 | V1.2 + V2.1 + V3.7 + V5.3 | 1.1922 | 0.05549 | **新组合** V5.3(Gate)上榜 |
| 9 | V2.1 + V2.4 + V3.7 + V4.4 | 1.1550 | 0.05659 | 高 IC 兼顾 TR |
| 10 | V1.2 + V2.1 + V3.7 + V5.1 | 1.2014 | 0.05560 | **V5.1 在 TOP 10 占 3 席** |
| 11 | V2.4 + V3.3 + V3.7 + V4.4 | 1.1468 | 0.05599 | 剪枝+多样性组合 |
| 12 | V1.2 + V2.8 + V3.7 + V4.1 | 1.0927 | 0.05706 | GC 双核 + V1.2+V3.7 |
| 13 | V0.3 + V3.7 + V4.0 + V5.1 | 1.1462 | 0.05663 | V4.0+ V5.1 对 TR 有益 |
| 14 | V1.2 + V3.7 + V4.0 + V5.1 | 1.1462 | 0.05663 | V1.2 替代 V0.3(=V1.0) |
| 15 | V2.8 + V3.7 + V4.8 + V5.1 | 1.1066 | 0.05691 | CosLR 系列+Attention |

### 按 IC 排名（去重 V5.0 等价组合）

| # | 组合 | top_return | IC | 备注 |
|:---:|------|:------:|:------:|------|
| **1** | **V2.8 + V4.0 + V5.1 + V5.6** | **0.9310** | **0.05772** | **★ IC 冠军** |
| 2 | V4.0 + V4.7 + V5.1 + V5.6 | 0.9104 | 0.05770 | V4.7(R-Drop+Kendall) |
| 3 | V3.7 + V4.0 + V5.1 + V5.6 | 0.9702 | 0.05764 | V3.7 提升 TR，IC 略降 |
| 4 | V2.8 + V4.0 + V5.5 + V5.6 | 0.8493 | 0.05766 | V5.5(All-Horizon R-Drop) |
| 5 | V2.8 + V4.0 + V4.1 + V5.5 | 0.9350 | 0.05764 | V4.1+ V5.5 组合 |
| 6 | V4.0 + V4.1 + V4.7 + V5.1 | 0.8789 | 0.05757 | V4 系列内部组合 |
| 7 | V2.8 + V4.0 + V4.8 + V5.5 | 0.7720 | 0.05758 | CosLR 系列 |
| 8 | V2.3 + V4.0 + V5.1 + V5.6 | 0.8462 | 0.05757 | V2.3(CD) 替代 V2.8 |
| 9 | V2.8 + V4.7 + V5.1 + V5.6 | 0.8284 | 0.05753 | V4.7 替代 V4.0 |
| 10 | V2.8 + V4.0 + V4.7 + V5.6 | 0.7660 | 0.05752 | 无 V5.1 的 IC 组合 |

### 按综合得分排名（去重 V5.0 等价组合）

| # | 组合 | top_return | IC | composite_z |
|:---:|------|:------:|:------:|:------:|
| **1** | **V1.2 + V3.7 + V4.1 + V5.1** | **1.1606** | **0.05668** | **3.99** |
| 2 | V2.8 + V3.7 + V5.1 + V5.6 | 1.0275 | 0.05747 | 3.78 |
| 3 | V2.8 + V3.7 + V4.8 + V5.1 | 1.1066 | 0.05691 | 3.71 |
| 4 | V1.0 + V3.7 + V4.0 + V5.1 | 1.1462 | 0.05663 | 3.67 |
| 5 | V3.7 + V4.0 + V4.8 + V5.1 | 1.0684 | 0.05709 | 3.56 |
| 6 | V3.7 + V4.0 + V4.1 + V5.1 | 1.0336 | 0.05726 | 3.54 |
| 7 | V2.8 + V3.7 + V4.1 + V5.1 | 1.0450 | 0.05719 | 3.49 |
| 8 | V3.7 + V4.0 + V5.1 + V5.6 | 0.9702 | 0.05764 | 3.43 |
| 9 | V1.0 + V3.7 + V4.1 + V5.1 | 1.1462 | 0.05663 | 3.37 |
| 10 | V2.5 + V3.7 + V4.0 + V5.6 | 0.9666 | 0.05712 | 2.95 |

---

##   模型出现频率分析（Top 50 × 3 维度 = 150 席）

| 排名 | 模型 | 出现次数/150 | 单人 TR | 单人 IC | 代际 | 角色 |
|:---:|------|:---:|:------:|:------:|:----:|------|
| 1 | **V4.0** | 70 | 1.1706 | 0.0559 | V4 Baseline | **IC 锚定者** — GC 基线提供排序骨架 |
| 2 | **V3.7** | 68 | 1.0408 | 0.0423 | V3 CD+FP65% | **TR 引擎** — 低 IC 但高多样性，TR 维度 33/50 |
| 3 | **V5.1** | 61 | 0.6099 | 0.0460 | V5 Attention | ** 多样性 MVP** — 单人最差，团队核心 |
| 4 | **V2.8** | 54 | 1.2100 | 0.0559 | V2 GC 冠军 | **IC 双核** — 与 V4.0 形成 GC 双锚 |
| 5 | **V1.2** | 45 | 1.3533 | 0.0530 | V1 冠军 | **TR 稳定器** — TR 维度 31/50 |
| 6 | V4.1 | 36 | 1.4745 | 0.0535 | V4 冠军 | 单人冠军，综合组合核心 |
| 7 | V5.6 | 33 | 1.2221 | 0.0525 | V5 Mixup | IC 辅助 — 22/50 IC 维度 |
| 8 | V1.0 | 28 | 1.1365 | 0.0532 | V1 Baseline | **TR 新星** — 朴素=多样化 |
| 9 | V2.1 | 25 | 0.9784 | 0.0519 | V2 Kendall | TR 辅助 — 20/50 TR 维度 |
| 10 | V5.5 | 18 | 0.8861 | 0.0534 | V5 All-Horizon | IC 维度 18/50 — 高 IC 但对 TR 有害 |
| 11 | V2.3 | 17 | 1.3336 | 0.0440 | V2 CD 冠军 | 与 V3.7 互补 |
| 12 | V4.8 | 14 | 1.0457 | 0.0530 | V4 R-Drop+CosLR | 综合维度 |
| 13 | V4.7 | 14 | 0.9642 | 0.0497 | V4 R-Drop+Kendall | IC 维度 14/50 |
| 14 | V3.2 | 10 | 1.1116 | 0.0524 | V3 R-Drop on Clean | TR 辅助 |
| 15 | V4.4 | 8 | 1.0937 | 0.0525 | V4 FP80%+GC | 偶尔上榜 |

---

##   场景化推荐

### 场景 1: 追求绝对收益最大化（推荐 ★）

```
V1.0 + V2.1 + V3.2 + V3.7
top_return = 1.2875  |  IC = 0.05547
```

**适用**：Top 1–10 集中持仓，不关心 IC，只追求最高回报。

**为什么有效**：V1.0（朴素基线）提供了与 V1.2（优化基线）不同的信号维度——V1.0 没有可学习 softmax 权重和强正则化，它对极端收益的"原始反应"与经过优化的 V1.2 形成了互补。V3.7（CD+FP65% 融合）继续担任 TR 引擎，V2.1（Kendall）和 V3.2（R-Drop on Clean）提供了更多正交信号。

### 场景 2: 追求 TR+IC 均衡（综合推荐 ★）

```
V1.2 + V3.7 + V4.1 + V5.1
top_return = 1.1606  |  IC = 0.05668  |  composite_z = 3.99
```

**适用**：既需要较高绝对收益，又需要稳定排序（3–50 只持仓）。

**为什么有效**：V4.1（单人 TR 冠军 371.56%）提供主攻火力，V3.7 提供防御多样性，V1.2 提供稳定排序，**V5.1（Factor Attention）是秘密武器**——它作为全系列单人最差模型，却提供了其他三个模型完全不具备的正交信号维度，大幅提升了 IC。

### 场景 3: 追求最高 IC（排序精度）

```
V2.8 + V4.0 + V5.1 + V5.6
top_return = 0.9310  |  IC = 0.05772
```

**适用**：大规模选股（Top 100–500），需要最高的截面排序准确性。

**为什么有效**：V2.8+V4.0 两个 GC 基线形成排序稳定性双锚，V5.1 提供正交信号，V5.6（Reduced Mixup）的减弱数据增强在分散持仓中表现优异。IC=0.05772 超越了所有单人模型的历史 IC 记录。

### 场景 4: V5.1 不可用时的备选（保守）

```
V1.2 + V2.1 + V3.2 + V3.7
top_return = 1.2505  |  IC = 0.05539
```

**适用**：如果不信任 V5.1（单人 TR 确实太差），这是一个经过两次搜索验证的稳健选择。

---

##   跨搜索验证对比（旧搜索 vs 新搜索）

| 维度 | 旧搜索 (2026-06-27) | 新搜索 (2026-06-28) | 变化 |
|------|------|------|:---:|
| 候选模型 | V1.8–V3.8 + V1.2_copy (20)| V0.3–V5.8 (29) | +9 |
| 组合总数 | 4,845 | 23,751 | ×4.9 |
| 回测区间 | 20250102–20260609 (345d) | 20250102–20260608 (344d) | -1d |
| 旧 TR 冠军 | V2.1+V3.2+V3.7+V1.2_copy (1.2505) | V1.0+V2.1+V3.2+V3.7 (1.2875) | **+3.0%** |
| 旧 IC 冠军 | V2.0+V2.4+V2.7+V2.8 (0.0571) | V2.8+V4.0+V5.1+V5.6 (0.05772) | **+1.1%** |
| 旧综合冠军 | V2.1+V3.2+V3.7+V1.2_copy (z=5.40) | V1.2+V3.7+V4.1+V5.1 (z=3.99) | 不可比* |

> *综合 z-score 不可直接对比——因为均值/标准差基于不同的候选模型池计算

---

##   V5.1 专题：从灾难到 MVP 的完整分析

### 单人战: V5.1 为什么这么差？

| 指标 | V5.0(=V4.1) Baseline | V5.1 (Factor Attention) | vs Baseline |
|------|:------:|:------:|:------:|
| Top 1 年化 | 371.56% | 153.69% | **-58.6%** |
| Top_Return | 1.4745 | 0.6099 | **-58.6%** |
| IC | 0.0535 | 0.0460 | -14.0% |
| ICIR | 0.6064 | 0.4045 | -33.3% |
| Q1 2025 收益 | 2.3214% | -0.0703% | **负收益** |

4-head Self-Attention on 960 factors → 960×960 attention matrix → 在 ~4 年训练数据上严重过拟合。

### 团队战: V5.1 为什么这么重要？

**V5.1 的预测信号与其他所有模型的相关性极低**——这是它单人失败的原因（信号质量差），也是它团队价值的原因（信号方向不同）。

在四人组中：
- V5.1 与其他模型的 **daily z-score 相关性最低**（因为它使用了完全不同的架构来生成预测）
- V5.1 对 IC 的贡献远大于对 TR 的贡献——它的信号在中等排名股票上有用，在极端 top-1 股票上无用
- 这就是为什么 V5.1 在 IC 维度出现 24/50 次，在 TR 维度仅 11/50 次

### 使用 V5.1 的建议

| 场景 | 是否包含 V5.1 | 理由 |
|------|:---:|------|
| Top 1–3 集中持仓 | ❌ 不推荐 | 拖累极端收益 |
| Top 5–20 中等持仓 | ⚠️ 可选 | 提升排序稳定性 |
| Top 50–500 分散持仓 | ✅ 推荐 | IC 提升显著 |
| 需要最高 IC/ICIR | ✅ 强烈推荐 | 提供不可替代的正交信号 |

---

##   最终推荐

### 实盘首选（TR 最大化）

```
V1.0 + V2.1 + V3.2 + V3.7
```
- top_return = **1.2875**（29 模型 × 23,751 组合中最优）
- IC = 0.05547
- 比旧冠军 TR 提升 3.0%

### 实盘备选（TR+IC 均衡）

```
V1.2 + V3.7 + V4.1 + V5.1
```
- top_return = 1.1606, IC = 0.05668
- 综合得分 23,751 组中最高

### 使用方式

修改 `mixed_model/ensemble_analysis.ipynb` 的 Cell 2：

```python
# 追求 TR 最大化（推荐）
ENSEMBLE_MODELS = ['V1.0', 'V2.1', 'V3.2', 'V3.7']

# 追求 TR+IC 均衡
ENSEMBLE_MODELS = ['V1.2', 'V3.7', 'V4.1', 'V5.1']
```

---

*完整数据：`/tmp/ensemble_search/full_results.csv`（23,751 行）*
*摘要 JSON：`/tmp/ensemble_search/summary.json`*
*搜索脚本：`mixed_model/search_best_ensemble.py`*
*结果已保存至 `/home/claude/ensemble_results.md`*
